name: synword_flutter_cubit_application
description: Anti-plagiarism mobile application.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  poseidon:
    path: ./poseidon/

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  hexcolor: ^2.0.6
  flutter_native_splash: ^1.3.3
  blur: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_native_splash:
  android: true
  color: "#301B28"
  image: assets/images/first_logo.png
  android_gravity: center
  android12: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/first_logo.png
    - assets/images/second_logo.png
    - assets/images/icons/hamburger.png
    - assets/images/icons/upload.png
    - assets/images/icons/close.png
    - assets/images/icons/copy.png
    - assets/images/icons/paste.png
    - assets/images/icons/error.png
    - assets/images/icons/info.png
    - assets/images/icons/pdf.png
    - assets/images/icons/docx-file.png
    - assets/images/icons/back-button.png
    - assets/images/icons/account.png

    - assets/images/icons/language-selection-dialog/radio-button-filled.png
    - assets/images/icons/language-selection-dialog/radio-button-not-filled.png
    - assets/images/icons/language-selection-dialog/russia.png
    - assets/images/icons/language-selection-dialog/united-states.png

    - assets/images/icons/menu/clock.png
    - assets/images/icons/menu/feedback.png
    - assets/images/icons/menu/instagram.png
    - assets/images/icons/menu/languages.png
    - assets/images/icons/menu/premium.png
    - assets/images/icons/menu/wallet.png

    - assets/images/premium-page/coins.png
    - assets/images/premium-page/crown.png
    - assets/images/premium-page/point.png
    - assets/images/premium-page/correct.png

    - assets/images/coin-page/coins.png
    - assets/images/coin-page/cart.png
    - assets/images/coin-page/info.png
    - assets/images/coin-page/gift-box.png
    - assets/images/coin-page/premium.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Waxe
      fonts:
        - asset: assets/fonts/Waxe.ttf
    - family: Araboto-Medium
      fonts:
        - asset: assets/fonts/Araboto-Medium-400.ttf
    - family: Cabrion
      fonts:
        - asset: assets/fonts/Cabrion-Regular.ttf
    - family: Roves-Sans-Reg-Rough
      fonts:
        - asset: assets/fonts/Roves-Sans-Reg-Rough.otf
    - family: Audrey
      fonts:
        - asset: assets/fonts/Audrey-Normal.otf
    - family: Isidora-Soft-Alt
      fonts:
        - asset: assets/fonts/Isidora-Soft-Alt-SemiBold.otf